### ISSUE TITLE
will this work on my pc ?

### ISSUE THREAD

**Issue by iam-siphon** [prolix-oc/Refyne#15]
Will this work on a rx6600 and a 12th gen i3 12100 ?

**Comment by luke-beep** [comment]
Yes.

**Comment by prolix-oc** [comment]
Yes, There should be no issues running this script on your hardware configuration. If you encounter any errors or the script breaks something, you can also join the [Discord](https://discord.gg/ffW3vCpGud) server for more direct assistance and troubleshooting as well.
