### ISSUE TITLE
"[2] Generate System Report" is replaced with "Enter number choice here:"

### ISSUE THREAD

**Issue by heapybruh** [prolix-oc/Refyne#19]
![image](https://github.com/prolix-oc/Refyne/assets/63428380/bc4ac0a0-f657-4d2d-b05c-35103b67ac4e)

It works fine when you select it but it's just not showing up.
EDIT: I ran the script once again and it printed all choices fine. Why wasn't it working on the first try tho? 🤔 

```powershell
Write-ColorOutput -InputObject  "You're currently running $($OSVersion)! Nice, let's get started." -ForegroundColor Green
Write-ColorOutput -InputObject "`nOptions:`n" -ForegroundColor DarkGray
if (Test-Path $RegistryBackupPath -PathType Leaf) { Write-ColorOutput -InputObject "[1] Run Refyne                      [5] Revert Changes" -ForegroundColor Gray } else { Write-ColorOutput -InputObject "[1] Run Refyne" -ForegroundColor Gray }
Write-ColorOutput -InputObject "[2] Generate System Report" -ForegroundColor Gray
Write-ColorOutput -InputObject "[3] Optimize PowerShell" -ForegroundColor Gray
Write-ColorOutput -InputObject "[4] Activate Windows" -ForegroundColor Gray
```

**Comment by luke-beep** [comment]
That's a great question, it might've been a buffer error. Were you modifying the width and height of the environment (terminal) during the initial run?

**Comment by heapybruh** [comment]
> Were you modifying the width and height of the environment (terminal) during the initial run?  
I resized the terminal after that happened.

**Comment by luke-beep** [comment]
I suppose that makes sense.

**Comment by luke-beep** [comment]
Our plan is to only physically support VT's.
