### ISSUE TITLE
Mouse n keyboard off

### ISSUE THREAD

**Issue by dunno420** [prolix-oc/Refyne#20]
I had 2 issues, the first one, the script didnt run, it just was openning as notepad, when i RMB n force it to PS, it just open and close fast, without showing anything, Tryed every version, from 0.1.0-0.0.5, just with the EasyStart.bat it worked. 

When I finally got it, I used version 0.1.0, but the mouse and keyboard simply stopped when Windows started, in the BIOS it worked normally, even in the Windows repair screen, but when it loaded normally, the keyboard and mouse they simply died, even changing ports they were not recognized, but all other things that were connected, such as the wifi dongle and joystick, seemed to work normally, only the keyboard and mouse did not work.

**Comment by luke-beep** [comment]
Hi @dunno420, 

Would you mind listing your current hardware?

**Comment by dunno420** [comment]
b450m steel legend
2x8gb 3200 walram
r5 2600x
rtx 2060
seasonic 600w 

kb hayom tc-3218
mouse redragon cobra m711

**Comment by luke-beep** [comment]
Closing this as we're working on a fix.
