### ISSUE TITLE
Embedded CEF and Chromium stop working.

### ISSUE THREAD

**Issue by SkylerGhostly** [prolix-oc/Refyne#23]
This is going to see a bit out there, but after running this script, most programs that utilize [CEF](https://github.com/chromiumembedded/cef) no longer work correctly or at all.

One very odd example is Second Life. I know, I know.... It uses CEF and other services around it to provide features like viewing web-pages or talking via voice chat.

Here's my steps to reproduce:
1. Clean-Install Windows 11 Pro For Workstations.
2. Install the Second Life viewer.
3. Check if the login webpage loads (it does)
4. Run Refyne and run tweaks.
5. Run Second Life Viewer again (login webpage fails to load)

There's a few other applications this happens to, but this is the most glaring one as Second Life relies quite heavily on CEF, Vivox Voice, and FMOD streaming. All of which break after running Refyne. 

EDIT: I've also cleanly reinstalled Windows twice, each time everything worked fine until Refyne was ran.  Revert changes does not work, and a restore point was not created.

**Comment by nvapi** [comment]
The issue also appears on Windows 10, for me though, it seems to just open Chromium Based Apps like Spotify, Steelseries GG really slow (15+ sec)

**Comment by luke-beep** [comment]
Hello,

To help us troubleshoot this issue, please provide your hardware information.

**Comment by SkylerGhostly** [comment]
> Hello,
> 
> To help us troubleshoot this issue, please provide your hardware information.

Sure, here ya go: 
OS: Windows 11 Pro for Workstations (23H2 22631.3447)
CPU: AMD Ryzen 7 3800x @ 4.2 GHZ
RAM: 4x8GB Corsair Vengeance LPX @ 3200MHZ (XMP)
MOBO: ASUS TUF x570 Plus Wifi
GPU: EVGA RTX 2070 Super XC 8GB
SSD: Samsung 980 Evo 1TB NVME

Let me know if you need any more information.

**Comment by luke-beep** [comment]
Thank you for providing this information.

I have previous experience with CEF, and anticipate that Blink should remain unaffected by this script. I will conduct a thorough review of the recent internal updates and cross-reference them with the open and closed issues on CEF's GitHub.

**Comment by luke-beep** [comment]
> > Hello,
> > To help us troubleshoot this issue, please provide your hardware information.
> 
> Sure, here ya go: OS: Windows 11 Pro for Workstations (23H2 22631.3447) CPU: AMD Ryzen 7 3800x @ 4.2 GHZ RAM: 4x8GB Corsair Vengeance LPX @ 3200MHZ (XMP) MOBO: ASUS TUF x570 Plus Wifi GPU: EVGA RTX 2070 Super XC 8GB SSD: Samsung 980 Evo 1TB NVME
> 
> Let me know if you need any more information.

Would you be willing to join the linked Discord server for troubleshooting purposes? If you are unable to do so, please let us know.

**Comment by nvapi** [comment]
> > > Hello,
> > > To help us troubleshoot this issue, please provide your hardware information.
> > 
> > 
> > Sure, here ya go: OS: Windows 11 Pro for Workstations (23H2 22631.3447) CPU: AMD Ryzen 7 3800x @ 4.2 GHZ RAM: 4x8GB Corsair Vengeance LPX @ 3200MHZ (XMP) MOBO: ASUS TUF x570 Plus Wifi GPU: EVGA RTX 2070 Super XC 8GB SSD: Samsung 980 Evo 1TB NVME
> > Let me know if you need any more information.
> 
> Would you be willing to join the linked Discord server for troubleshooting purposes? If you are unable to do so, please let us know.

I did just join, can post hardware information there, made a thread in the #support channel.

**Comment by SkylerGhostly** [comment]
> > > Hello,
> > > To help us troubleshoot this issue, please provide your hardware information.
> > 
> > 
> > Sure, here ya go: OS: Windows 11 Pro for Workstations (23H2 22631.3447) CPU: AMD Ryzen 7 3800x @ 4.2 GHZ RAM: 4x8GB Corsair Vengeance LPX @ 3200MHZ (XMP) MOBO: ASUS TUF x570 Plus Wifi GPU: EVGA RTX 2070 Super XC 8GB SSD: Samsung 980 Evo 1TB NVME
> > Let me know if you need any more information.
> 
> Would you be willing to join the linked Discord server for troubleshooting purposes? If you are unable to do so, please let us know.

I can absolutely join the discord. Thank you.
